platform:
  - x64

init:
  - git config --global core.autocrlf input

environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Check that we have the expected version and architecture for Python
  - "python --version"
  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"
  - "pip install -r requirements.txt"

build_script:
  - "python build.py build"

test: off

artifacts:
- path: build\exe.win-amd64-3.6
  name: Fuzzy Eve Notifier-win32-x64-$(APPVEYOR_REPO_TAG_NAME)

deploy:
- provider: GitHub
  auth_token:
    secure: XzF+tv+eNt5kVFVCR+vRzieXMuQuiIm59sNqopHv9w3VXu9Watx7fn/s+r93nVF0
  artifact: /.*\.zip/
  on:
    appveyor_repo_tag: true